### ISSUE TITLE
ElementCollectionField breaks with NPE

### ISSUE THREAD

**Issue by pleku** [viritin/viritin#103]
When adding a new element to ElementCollectionField and `allowRemovingItems = false`, a NPE is fired for "description button" from https://github.com/viritin/viritin/blob/master/src/main/java/org/vaadin/viritin/fields/ElementCollectionField.java#L147
To reproduce, just call
```java
    elementCollectionField.setAllowRemovingItems(false); 
    elementCollectionField.addElement(new Bean());
```
Calling ```setAllowRemovingItems(true)``` before make issue not reproduce, but won't work as a workaround since calling ```setAllowRemovingItems(false)``` afterwards will not remove the delete buttons. 

Stacktrace:
Caused by: java.lang.NullPointerException
	at org.vaadin.viritin.fields.ElementCollectionField.setPersisted(ElementCollectionField.java:147)
	at org.vaadin.viritin.fields.ElementCollectionField.onElementAdded(ElementCollectionField.java:218)
	at org.vaadin.viritin.fields.AbstractElementCollection.setInternalValue(AbstractElementCollection.java:419)
	at org.vaadin.viritin.fields.AbstractElementCollection.setInternalValue(AbstractElementCollection.java:42)
	at com.vaadin.ui.AbstractField.readValueFromProperty(AbstractField.java:1293)
	at com.vaadin.ui.AbstractField.valueChange(AbstractField.java:1286)
	at com.vaadin.data.util.AbstractProperty.fireValueChange(AbstractProperty.java:271)
	at com.vaadin.data.util.TransactionalPropertyWrapper.fireValueChange(TransactionalPropertyWrapper.java:131)
	at com.vaadin.data.util.TransactionalPropertyWrapper$1.valueChange(TransactionalPropertyWrapper.java:55)
	at com.vaadin.data.util.AbstractProperty.fireValueChange(AbstractProperty.java:271)
	at com.vaadin.data.util.MethodProperty.fireValueChange(MethodProperty.java:765)
	at com.vaadin.data.util.MethodProperty.setValue(MethodProperty.java:648)
	at com.vaadin.data.util.TransactionalPropertyWrapper.setValue(TransactionalPropertyWrapper.java:94)
	at org.vaadin.viritin.fields.AbstractElementCollection.getAndEnsureValue(AbstractElementCollection.java:211)
	at org.vaadin.viritin.fields.AbstractElementCollection.addElement(AbstractElementCollection.java:343)

**Comment by mstahv** [comment]
Thanks, good catch!
