### ISSUE TITLE
NPE in ListContainer.getNestedPropertyType

### ISSUE THREAD

**Issue by perjo** [viritin/viritin#117]
I have a simple project trying to use Viritin 1.38 MTable + LazyList along the lines describes in https://vaadin.com/web/matti/blog/-/blogs/connecting-large-amounts-of-data-to-ui (but on Java 7). 

I can not get this to work, I get a strange NPE in `ListContainer.getNestedPropertyType` (full stack trace below). 

The setup is simple 

    LazyList<SampleDTO> lazyList = new LazyList<>(pagingProvider, countProvider);

    table = new MTable<>(lazyList).withProperties(PROP_IDENTITY).withColumnHeaders(IDENTITY_HEADER).withFullWidth();

where `PROP_IDENTITY` is the name of a property in `SampleDTO` which is a Java bean according to all definitions (serializable, no-arg constructor, setters and getters). 

It all crashes on line 282 in `ListContainer` 

    Class<?> type = bean.getDynaProperty(name).getType();
 
where `name` is the string in `PROP_IDENTITY` but this is not present as key in the `WrapDynaClass` `propertiesMap` which only contains an entry for key "class". 

Any ideas about this? 

# Full stack trace

10:42:13,194 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/vaaadin].[MyUIServlet]] (http-127.0.0.1/127.0.0.1:8080-4) JBWEB000236: Servlet.service() for servlet MyUIServlet threw exception: java.lang.NullPointerException
        at org.vaadin.viritin.ListContainer.getNestedPropertyType(ListContainer.java:282) [viritin-1.38.jar:1.38]
        at org.vaadin.viritin.ListContainer.getType(ListContainer.java:244) [viritin-1.38.jar:1.38]
        at com.vaadin.ui.AbstractSelect.getType(AbstractSelect.java:776) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.ui.Table.getVisibleCellsNoCache(Table.java:2170) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.ui.Table.refreshRenderedCells(Table.java:1711) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.ui.Table.attach(Table.java:4246) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:616) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:669) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:576) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:210) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.ui.AbstractOrderedLayout.addComponent(AbstractOrderedLayout.java:98) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.navigator.Navigator$ComponentContainerViewDisplay.showView(Navigator.java:191) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:575) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:527) [vaadin-server-7.5.8.jar:7.5.8]
        at se.databyran.vaadin.MyUI.init(MyUI.java:46) [classes:]
        at com.vaadin.ui.UI.doInit(UI.java:675) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:214) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408) [vaadin-server-7.5.8.jar:7.5.8]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:351) [vaadin-server-7.5.8.jar:7.5.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final.jar:1.0.2.Final]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Alpha1-redhat-4.jar:7.2.0.Alpha1-redhat-4]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_21]

**Comment by mstahv** [comment]
Hi, can you share the SampleDTO implementation with me for inspection? Feel free to use matti ät vaadin dot com if you cannot publish it online.

cheers,
matti

**Comment by perjo** [comment]
Class declaration below, but I now suspect that find myself in some kind of jar hell. I also got an NoSuchMethodError when a BeanUtil method was called. 


    public class SampleDTO implements Serializable {
    
       private static final long serialVersionUID = 1L;

       private long id;

       private String identity;

       public SampleDTO() {
       }

       public long getId() {
            return id;
       }

       public String getIdentity() {
           return identity;
       }

       public void setId(long id) {
           this.id = id;
       }

       public void setIdentity(String identity) {
            this.identity = identity;
       }
    }

**Comment by perjo** [comment]
Viritin depends on commons-beanutils 1.9.2, but our project by means of dependency management overrode this to version 1.8.3 which caused the error.
