### ISSUE TITLE
MTable ListContainer throws NestedNullException when NestedProperty value is null

### ISSUE THREAD

**Issue by ninjanik** [viritin/viritin#123]
Vaadin 7.7.5
Viritin 1.40
Commons BeanUtils 1.9.2

MTable using ListContainer doesn't handle null values for nested property objects.
```
public class Foo {
	String id;
	String description;
	Bar optionalBar;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Bar getOptionalBar() {
		return optionalBar;
	}
	public void setOptionalBar(Bar optionalBar) {
		this.optionalBar = optionalBar;
	}	
}
```
```
public class Bar {

	String id;
	String description;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}	
}
```
```
void init(){
        Bar b = new Bar();
		b.setId("bar1");
		
		Foo f1 = new Foo();
		f1.setId("foo1");
		f1.setDescription("desc1");
		f1.setOptionalBar(b);
		
		Foo f2 = new Foo();
		f2.setId("foo2");
		f2.setDescription("desc2");
//		f2.setOptionalBar(b);
		
		table = new MTable<Foo>(f1,f2)
					.withProperties("id", "optionalBar.id").withFullWidth();
}
```
throws...
com.vaadin.ui.Table$CacheUpdateException: Error during Table cache update.
...
Caused by: java.lang.RuntimeException: org.apache.commons.beanutils.NestedNullException: Null property value for 'optionalBar.id' on bean class 'class com.victor.views.Foo'
	at org.vaadin.viritin.ListContainer$DynaBeanItem$DynaProperty.getValue(ListContainer.java:483)
	at com.vaadin.ui.Table.formatPropertyValue(Table.java:4123)
	at com.vaadin.ui.Table.getPropertyValue(Table.java:4067)
	at com.vaadin.ui.Table.parseItemIdToCells(Table.java:2349)
	at com.vaadin.ui.Table.getVisibleCellsNoCache(Table.java:2188)
	at com.vaadin.ui.Table.refreshRenderedCells(Table.java:1710)

[FooBar-error.txt](https://github.com/viritin/viritin/files/93535/FooBar-error.txt)

**Comment by ninjanik** [comment]
MTable using ListContainer doesn't handle null values for nested property objects.

public class Foo {
	String id;
	String description;
	Bar optionalBar;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Bar getOptionalBar() {
		return optionalBar;
	}
	public void setOptionalBar(Bar optionalBar) {
		this.optionalBar = optionalBar;
	}	
}

public class Bar {

	String id;
	String description;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}	
}

void init(){
                Bar b = new Bar();
		b.setId("bar1");
		
		Foo f1 = new Foo();
		f1.setId("foo1");
		f1.setDescription("desc1");
		f1.setOptionalBar(b);
		
		Foo f2 = new Foo();
		f2.setId("foo2");
		f2.setDescription("desc2");
//		f2.setOptionalBar(b);
		
		table = new MTable<Foo>(f1,f2)
					.withProperties("id", "optionalBar.id").withFullWidth();
}

[FooBar-error.txt](https://github.com/viritin/viritin/files/93535/FooBar-error.txt)

**Comment by ninjanik** [comment]
thanks for fixing this so quickly!
