### ISSUE TITLE
NPE when container is empty

### ISSUE THREAD

**Issue by rlsutton1** [viritin/viritin#210]
I get the following stack trace when my container is empty, I've also supplied a minimal code example to reproduce the problem

java.lang.NullPointerException
	at org.vaadin.viritin.ListContainer.getSortableContainerPropertyIds(ListContainer.java:416)
	at com.vaadin.ui.Table.getSortableContainerPropertyIds(Table.java:4897)
	at org.vaadin.viritin.fields.MTable.getSortableContainerPropertyIds(MTable.java:356)
	at com.vaadin.ui.Table.paintVisibleColumns(Table.java:3610)
	at com.vaadin.ui.Table.doPaintContent(Table.java:3361)
	at com.vaadin.ui.Table.paintContent(Table.java:3302)
	at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65)
	at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:145)
	at com.vaadin.server.communication.UIInitHandler.getInitialUidl(UIInitHandler.java:285)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:80)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364)

`public class TestGrid extends VerticalLayout implements View
{

	@Test
	public void test()
	{
	}

	class TestBean
	{
		String name;
		String SubName;

	}

	class ViritinProvider implements CountProvider, SortablePagingProvider<TestBean>
	{

		private static final long serialVersionUID = 1L;

		@Override
		public List<TestBean> findEntities(final int firstRow, final boolean sortAscending, final String property)
		{

			return new LinkedList<>();
		}

		@Override
		public int size()
		{
			return 0;
		}
	}

	@Override
	public void enter(ViewChangeEvent event)
	{
		ViritinProvider provider = new ViritinProvider();
		MTable<TestBean> allocationSelector = new MTable<>(provider, provider).withProperties("Name", "SubName")
				.withColumnHeaders("Campaign", "Allocation");

		allocationSelector.withFullWidth().withHeight("300px");
		TestGrid.this.addComponent(allocationSelector);

	}

}`

**Comment by mstahv** [comment]
Try passing in the actual TestBean.class in the constructor and then use lazyLoadFrom method to assign the "datasource". If it don't work, let me know.

I guess we should deprecate the constructors without type parameter or add this to documentation (both wiki and to Javadocs).

**Comment by rlsutton1** [comment]
Ok made the changes as below and it now works. Thanks. 
Deprecation and some Java Doc suggesting the correct approach would be great.

`		MTable<TestBean> allocationSelector = new MTable<>(TestBean.class).withProperties("Name", "SubName")
				.withColumnHeaders("Campaign", "Allocation");

		allocationSelector.lazyLoadFrom(provider, provider);
`
