### ISSUE TITLE
NoSuchElementException in lazyList.subList for toIndex == size()

### ISSUE THREAD

**Issue by larskn** [viritin/viritin#273]
This happens inside the ArrayList constructor in `return new ArrayList<>(super.subList(fromIndex, toIndex));`. For some reason in AbstractCollection.toArray() `it.hasNext()` returns true, but `it.next()` fails afterwards. Might have something to do with the LazyList Iterator implementation.

Simple sample to reproduce
```
public static void main(final String[] args) {
    final ArrayList<String> strings = new ArrayList<>();
    strings.add("a");
    strings.add("b");
    strings.add("c");
    strings.add("d");
    strings.add("e");
    strings.add("f");
    strings.add("g");
    strings.add("h");
    final LazyList<String> lazyList = new LazyList<>(
        firstRow -> strings.subList(firstRow, Math.min(firstRow + 2, strings.size() - 1)),
        () -> strings.size(),
        2);
    System.out.println("Works");
    lazyList.subList(0, strings.size() - 1);
    System.out.println("Does not work, but should work:");
    lazyList.subList(0, strings.size());
}
```

Causes this error:
```
Exception in thread "main" java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:364)
	at java.util.SubList$1.next(AbstractList.java:707)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at org.vaadin.viritin.LazyList.subList(LazyList.java:294)
	at main.MyMain.main(MyMain.java:42)
```

In reality this happens for example with MTable:
```
java.util.NoSuchElementException: null
	at java.util.AbstractList$Itr.next(AbstractList.java:364)
	at java.util.SubList$1.next(AbstractList.java:707)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at org.vaadin.viritin.LazyList.subList(LazyList.java:294)
	at org.vaadin.viritin.ListContainer.getItemIds(ListContainer.java:135)
	at com.vaadin.ui.Table.getItemIds(Table.java:2278)
	at com.vaadin.ui.Table.getVisibleCellsNoCache(Table.java:2224)
	at com.vaadin.ui.Table.refreshRenderedCells(Table.java:1747)
	at com.vaadin.ui.Table.enableContentRefreshing(Table.java:3278)
	at com.vaadin.ui.Table.changeVariables(Table.java:3120)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:627)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:461)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:411)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcollovati** [comment]
I think the problem is in the PagingProvider implementation;
subList **toIndex** is exclusive, so the minimum should be calculated between `firstRow + 2` and `strings.size()`  (without - 1)

**Comment by larskn** [comment]
Yes, you are right. Sorry, my bad. This issue can be closed. Thank you very much.
