### ISSUE TITLE
BrowserCookie AbstractMethodError.

### ISSUE THREAD

**Issue by gorishagh** [viritin/viritin#74]
Hello,

I am trying to set and read cookies via Viritin, however I get a runtime exception as following:
I would appreciate any help.

My Code:
Setting the cookie:
BrowserCookie.setCookie("nodeinfo", infoJson);  

Reading the cookie:
BrowserCookie.detectCookieValue("nodeinfo",new BrowserCookie.Callback() {		
			@Override
			public void onValueDetected(String value) {
				System.out.println("Value: " +  value);
			}
		});

The Runtime Exception:

java.lang.AbstractMethodError: org.vaadin.viritin.util.BrowserCookie$1.call(Lelemental/json/JsonArray;)V
	at com.vaadin.ui.JavaScript$1.call(JavaScript.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:291)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
	at com.vaadin.server.communication.PushHandler$3.run(PushHandler.java:176)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:255)
	at com.vaadin.server.communication.PushHandler.access$200(PushHandler.java:58)
	at com.vaadin.server.communication.PushHandler$1.onRequest(PushHandler.java:78)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:205)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
	at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.doService(Tomcat7Servlet30SupportWithWebSocket.java:67)
	at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:98)
	at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
	at com.vaadin.server.communication.PushRequestHandler.handleRequest(PushRequestHandler.java:148)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:350)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by mstahv** [comment]
Which version of Vaadin are you using? I think they changed some JSON library in 7.4 release and this looks like a regression due to it :-(

**Comment by gorishagh** [comment]
Thanks for your response. I am using 7.4.2. Is there any chance that Viritin will be compatible with Vaadin 7.4 anytime soon?

**Comment by mstahv** [comment]
The current version is pretty good for 7.3 users, so maybe I could stop support for that today. I have couple things to do before, but I'll try to get to this soon.

**Comment by mstahv** [comment]
WTF is this github doing? Not there yet, running some tests.

**Comment by gorishagh** [comment]
Great. Thanks.
